// supabase/functions/ugq-confirm-publish/index.ts
// Epic UGQ — Aug 2026: user-confirmed publish.
//
// Supersedes silent auto-publish (ugq-screen's AUTOPUBLISH_ENABLED, now off
// by default). The proposer now sees the full preview — question, both
// slider-end labels, web-search-grounded context, and (Aug 2026, NEW) a
// cover image when one was found — in the modal, and explicitly clicks
// Publish. THIS endpoint is what that click calls.
//
// Auth: user JWT required. Verifies the caller owns the proposal (a
// proposer can only publish their own questions) before doing anything.
//
// What it does:
//   1. Loads the proposal, checks ownership + status + that a usable preview
//      exists (preview_reframe.question) + that a topic was resolved
//      (auto_topic_id — required by ugq-publish).
//   2. Idempotent: if already published, just returns the existing
//      question_id rather than erroring — a proposer double-clicking Publish
//      (slow network, etc.) shouldn't see a scary error.
//   3. Calls ugq-publish server-to-server (x-cron-secret) with EXACTLY the
//      preview text the proposer saw — auto_published=true, same as the old
//      auto-publish path, so it still lands in the admin parallel-review
//      queue (this text was never fact-checked, that hasn't changed).
//   4. Best-effort, non-blocking: suggests up to 3 candidate authorities from
//      authority_registry via a quick LLM match, inserts them into
//      user_authority_suggestions (status='suggested'), and returns them so
//      the frontend can immediately ask "want to tag one of these?". A
//      failure here never fails the publish itself — the question is live
//      either way; worst case the user just doesn't get a suggestion this
//      time.
//   5. Sep 2026, NEW: generates the question's rendition(s) SYNCHRONOUSLY
//      before responding — see generateRenditionsNow. questions.
//      canonical_language always defaults to 'en' (every publish path here
//      writes English text — Stage B/the fast preview both produce English
//      regardless of what language the proposer originally submitted in),
//      so stub_question_renditions() stubs one 'pending' row per language
//      that applies to this question's location (see language_regions/
//      language_applies_to_location — genuinely 0, 1, or N rows depending
//      on which languages are active and mapped to its region, not always
//      exactly one 'hi' row); this claims and processes whatever got
//      stubbed immediately instead of waiting on the 1-min cron sweep.
//      Fails open, same posture as the authority-suggestion step: any
//      failure here leaves the affected stub(s) 'pending' for the cron
//      sweep to pick up later, never blocks or fails the publish response
//      itself.
//
//      Sep 2026, UPDATED: ugq-publish itself may now already have seeded
//      the proposer's own detected-language stub directly from their
//      own-language preview text (see preview_reframe.question_native,
//      generated by ugq-screen) and marked it 'published' before this even
//      runs — see this call's new detected_language/question_native/
//      slider_*_label_native fields below. This function's own guard
//      (`transform_status = 'pending'`) already handles that correctly: it
//      simply finds nothing left to claim for that language and no-ops, so
//      no change was needed here beyond passing those fields through.
//
// Epic X (video, NEW): for a video proposal, this is where the proposer's
// publish choice — raw_only / raw_plus_overlay — is actually made (not at
// capture time in ugq-submit, and not stored ahead of time) — the client
// sends video_publish_choice in this endpoint's request body at the moment
// the proposer clicks Publish, matching the design: the choice happens
// right before posting, alongside seeing the full preview. Required (400 if
// missing/invalid) whenever the proposal is a video submission; ignored for
// text/voice. A proposal stuck at status 'resubmit_requested' (leading
// framing, not yet re-recorded) already fails the existing status !==
// 'in_review' check below with a clear message — no separate guard needed
// for that case. ("raw_plus_avatar" was dropped Sep 2026 — no TTS/avatar
// synthesis backend exists.)

import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
};

function json(status: number, payload: unknown) {
  return new Response(JSON.stringify(payload), {
    status, headers: { ...corsHeaders, "Content-Type": "application/json" },
  });
}

type Authority = { id: string; name: string; domain: string; jurisdiction_level: string };

// Sep 2026, NEW — see header note §5. Claims and processes exactly the
// pending 'hi' stub for this question via generate-question-renditions'
// rendition_id param (the single-row counterpart to its normal FIFO cron
// batch). Swallows every error itself — this is fire-and-forget from the
// caller's perspective except for the await, which exists only to make
// "synchronous" actually synchronous, not to propagate failure.
//
// Sep 2026, GENERALIZED: used to hardcode language_code='hi' and claim at
// most one row (renamed from generateHindiRenditionNow) — assumed exactly
// one non-English language could ever need synchronous generation at
// publish time. Now processes every 'pending' rendition stub_question_
// renditions() created for this question, whatever languages those are —
// zero code change needed here when a new language (Tamil, Telugu, etc.)
// starts getting stubbed by that trigger. Each rendition is independent and
// already fails open on its own, so processing them concurrently doesn't
// change that posture.
async function generateRenditionsNow(
  supabaseUrl: string, cronSecret: string, adminSb: ReturnType<typeof createClient>, questionId: string,
) {
  let pendingRenditions: { id: string }[] = [];
  try {
    const { data } = await adminSb.from("question_renditions")
      .select("id")
      .eq("question_id", questionId)
      .eq("transform_status", "pending");
    pendingRenditions = data ?? [];
  } catch (e) {
    console.error(JSON.stringify({ tag: "ugq-confirm-publish.rendition_list_exception", message: (e as Error).message }));
    return;
  }
  if (!pendingRenditions.length) return; // already claimed/processed/seeded, or nothing stubbed — nothing to do

  await Promise.all(pendingRenditions.map(async (rendition) => {
    try {
      const res = await fetch(`${supabaseUrl}/functions/v1/generate-question-renditions`, {
        method: "POST",
        headers: { "content-type": "application/json", "x-cron-secret": cronSecret },
        body: JSON.stringify({ rendition_id: rendition.id }),
      });
      if (!res.ok) {
        const text = await res.text().catch(() => "");
        console.error(JSON.stringify({ tag: "ugq-confirm-publish.rendition_failed", rendition_id: rendition.id, status: res.status, body: text.slice(0, 300) }));
      }
    } catch (e) {
      console.error(JSON.stringify({ tag: "ugq-confirm-publish.rendition_exception", rendition_id: rendition.id, message: (e as Error).message }));
    }
  }));
}

serve(async (req) => {
  if (req.method === "OPTIONS") return new Response("ok", { headers: corsHeaders });
  if (req.method !== "POST") return json(405, { ok: false, error: "METHOD_NOT_ALLOWED" });

  const SUPABASE_URL = Deno.env.get("SUPABASE_URL")!;
  const SERVICE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
  const ANON_KEY = Deno.env.get("SUPABASE_ANON_KEY")!;
  const CRON_SECRET = Deno.env.get("CRON_SECRET") ?? "";
  const ANTHROPIC_API_KEY = Deno.env.get("ANTHROPIC_API_KEY") ?? "";
  // Off switch for the authority-suggestion step specifically — publish
  // itself is never gated by this.
  const AUTHORITY_SUGGEST_ENABLED = (Deno.env.get("UGQ_AUTHORITY_SUGGEST_ENABLED") ?? "true") === "true";

  try {
    // ── Identity ─────────────────────────────────────────────────────────
    const authHeader = req.headers.get("Authorization") ?? "";
    if (!authHeader.startsWith("Bearer ")) return json(401, { ok: false, error: "UNAUTHORIZED" });
    const userSb = createClient(SUPABASE_URL, ANON_KEY, { global: { headers: { Authorization: authHeader } } });
    const { data: { user } } = await userSb.auth.getUser();
    if (!user) return json(401, { ok: false, error: "UNAUTHORIZED" });

    const body = await req.json().catch(() => ({}));
    const proposalId = typeof body.proposal_id === "string" ? body.proposal_id : "";
    if (!proposalId) return json(400, { ok: false, error: "MISSING_PROPOSAL_ID" });

    const adminSb = createClient(SUPABASE_URL, SERVICE_KEY);

    const { data: proposal } = await adminSb.from("user_question_proposals")
      .select("id, user_id, status, preview_reframe, auto_topic_id, reframed_question_id, source_url, input_mode, video_recording_path, video_duration_seconds")
      .eq("id", proposalId).maybeSingle();
    if (!proposal) return json(404, { ok: false, error: "NOT_FOUND" });
    if (proposal.user_id !== user.id) return json(403, { ok: false, error: "FORBIDDEN", message: "You can only publish your own proposals." });

    // Idempotent — a double-click or retry after a slow response shouldn't error.
    if (proposal.status === "published" && proposal.reframed_question_id) {
      return json(200, { ok: true, already_published: true, question_id: proposal.reframed_question_id, suggested_authorities: [] });
    }
    // Epic X, NEW: friendlier message than the generic NOT_READY below for
    // the one specific case a proposer is likely to actually hit — a video
    // that failed the framing gate and is waiting on a re-record.
    if (proposal.status === "resubmit_requested") {
      return json(409, {
        ok: false, error: "RESUBMIT_REQUIRED",
        message: "This question needs to be re-recorded before it can be published.",
      });
    }
    if (proposal.status !== "in_review") {
      return json(409, {
        ok: false, error: "NOT_READY",
        message: `Proposal is '${proposal.status}' — it needs to clear screening (status 'in_review') before it can be published.`,
      });
    }

    // Epic X, NEW: publish choice is made HERE, not at capture time — see
    // header note. Required only for video proposals.
    const isVideoSubmission = proposal.input_mode === "video" && !!proposal.video_recording_path;
    // Sep 2026: "raw_plus_avatar" dropped — no TTS/avatar synthesis backend
    // exists, so it was never a real choice. Revisit if that infra is built.
    const videoPublishChoice = ["raw_only", "raw_plus_overlay"].includes(body.video_publish_choice)
      ? body.video_publish_choice as string : null;
    if (isVideoSubmission && !videoPublishChoice) {
      return json(400, {
        ok: false, error: "MISSING_PUBLISH_CHOICE",
        message: "Choose how to publish this video: raw only, or raw with a neutral overlay.",
      });
    }

    const preview = proposal.preview_reframe as Record<string, unknown> | null;
    const previewQuestion = typeof preview?.question === "string" ? preview.question.trim() : "";
    if (!previewQuestion) {
      return json(409, {
        ok: false, error: "NO_PREVIEW",
        message: "No preview is ready for this proposal yet. Try re-screening it first.",
      });
    }
    const topicId = typeof proposal.auto_topic_id === "string" ? proposal.auto_topic_id : "";
    if (!topicId) {
      return json(409, {
        ok: false, error: "NO_TOPIC",
        message: "This proposal doesn't have a topic assigned yet, so it can't be published. Try re-screening it, or contact support.",
      });
    }

    // ── Cover image ───────────────────────────────────────────────────────────
    // UGQ questions have no news_item/cluster — assign_question_cover()
    // (the editorial pipeline's image assignment) can never find them an
    // image, that whole system only knows about scraped news articles.
    // Rather than requiring a source_url from the proposer or paying for AI
    // generation, reuse the supporting_links the preview's web search ALREADY
    // found (same URLs backing context_summary) — same og:image/twitter:image
    // scraping technique enrich-images uses for the news pipeline, just
    // inlined here rather than shared (Deno edge functions can't import
    // across each other). Free, and the image comes from the same sources
    // that grounded the text, so it's contextually on-topic by construction.
    //
    // Aug 2026, NEW: ugq-screen now runs this SAME scrape at preview time
    // (see its attachCoverImage) so the "Here's how this looks" modal can
    // show the image BEFORE the user ever clicks Publish, instead of the
    // proposer publishing blind on this front. So this endpoint now prefers
    // that cached result — distinguishing "already attempted, found nothing"
    // (the cover_image_url key is present on preview_reframe, value null —
    // a legitimate outcome, don't retry) from "never attempted" (key absent
    // entirely — legacy preview_reframe rows written before this field
    // existed, or PREVIEW_ENABLED was off at screening time) — only the
    // latter falls back to a fresh fetch here, same as this endpoint always
    // did before ugq-screen took over the common case.
    //
    // The proposer's own optional "Source link" (proposal.source_url) —
    // captured at submit time — is still read here as a candidate too, for
    // the fresh-fetch fallback path only (ugq-screen's attachCoverImage
    // already folds it in for the cached-result path). Placed FIRST in the
    // candidate list when it IS used: a source the proposer deliberately
    // chose should win over an AI-found one if both happen to succeed.
    const supportingLinks = Array.isArray(preview?.supporting_links) ? preview.supporting_links : [];
    const proposalSourceUrl = typeof proposal.source_url === "string" && proposal.source_url.trim()
      ? proposal.source_url.trim() : null;
    const imageCandidates = [
      ...(proposalSourceUrl ? [proposalSourceUrl] : []),
      ...supportingLinks,
    ];
    const previewCoverImageAttempted = !!preview && Object.prototype.hasOwnProperty.call(preview, "cover_image_url");
    const cachedCoverImageRaw = previewCoverImageAttempted ? (preview as Record<string, unknown>).cover_image_url : undefined;
    const cachedCoverImageUrl = typeof cachedCoverImageRaw === "string" && cachedCoverImageRaw.trim()
      ? cachedCoverImageRaw.trim() : null;
    const coverImageUrl = previewCoverImageAttempted
      ? cachedCoverImageUrl
      : await findCoverImageFromLinks(imageCandidates);

    // ── Publish — reuses ugq-publish exactly as the (now-optional) auto-publish
    //    path in ugq-screen did, just triggered here by the user's click. ──────
    const pubResp = await fetch(`${SUPABASE_URL}/functions/v1/ugq-publish`, {
      method: "POST",
      headers: { "content-type": "application/json", "x-cron-secret": CRON_SECRET },
      body: JSON.stringify({
        proposal_id: proposalId,
        reframed_question: previewQuestion,
        topic_id: topicId,
        slider_low_label: typeof preview?.slider_low_label === "string" ? preview.slider_low_label : null,
        slider_high_label: typeof preview?.slider_high_label === "string" ? preview.slider_high_label : null,
        context_summary: typeof preview?.context_summary === "string" ? preview.context_summary : null,
        supporting_links: supportingLinks,
        cover_image_url: coverImageUrl,
        // Still true: this text was never fact-checked (the preview call has
        // no verification loop), so it still belongs in the same parallel
        // admin-review queue auto-publish used to feed — only WHO triggered
        // the publish changed, not how trustworthy the text is.
        auto_published: true,
        // Sep 2026, NEW — see header note §5 (updated). Lets ugq-publish
        // seed the proposer's own-language rendition directly when they
        // proposed in a non-English language; a no-op for English
        // proposals (these fields are simply absent/null on preview_reframe).
        detected_language: typeof preview?.detected_language === "string" ? preview.detected_language : null,
        question_native: typeof preview?.question_native === "string" ? preview.question_native : null,
        slider_low_label_native: typeof preview?.slider_low_label_native === "string" ? preview.slider_low_label_native : null,
        slider_high_label_native: typeof preview?.slider_high_label_native === "string" ? preview.slider_high_label_native : null,
        // Epic X, NEW.
        ...(isVideoSubmission ? {
          video_recording_path: proposal.video_recording_path,
          video_duration_seconds: proposal.video_duration_seconds,
          video_publish_choice: videoPublishChoice,
        } : {}),
      }),
    });
    const pubJson = await pubResp.json().catch(() => ({}));
    if (!pubResp.ok || !pubJson?.ok) {
      console.error(JSON.stringify({ tag: "ugq-confirm-publish.publish_failed", body: pubJson }));
      return json(502, { ok: false, error: "PUBLISH_FAILED", message: pubJson?.message ?? "Publish failed — please try again." });
    }
    const questionId = pubJson.question_id as string;

    // ── Authority suggestions (best-effort, never blocks the publish response) ─
    let suggestedAuthorities: Authority[] = [];
    if (AUTHORITY_SUGGEST_ENABLED && ANTHROPIC_API_KEY) {
      try {
        const { data: authorities } = await adminSb.from("authority_registry")
          .select("id, name, domain, jurisdiction_level")
          .limit(200);
        const candidates = (authorities ?? []) as Authority[];

        if (candidates.length > 0) {
          const sys =
            "You match a civic question to the most relevant authorities from a provided directory. " +
            "Return ONLY JSON: {\"authority_ids\":[\"id\",...]} — 0 to 3 ids, ONLY from the provided candidate " +
            "list, ordered most-relevant first. Empty array if nothing in the list is genuinely relevant — " +
            "never force a weak match.";
          const usr =
            `Question:\n"${previewQuestion}"\n\n` +
            `Background context:\n${typeof preview?.context_summary === "string" ? preview.context_summary : "(none)"}\n\n` +
            `Candidate authorities:\n` +
            candidates.map((a) => `- id=${a.id} :: ${a.name} (domain: ${a.domain}, level: ${a.jurisdiction_level})`).join("\n");

          const res = await fetch("https://api.anthropic.com/v1/messages", {
            method: "POST",
            headers: {
              "Content-Type": "application/json",
              "x-api-key": ANTHROPIC_API_KEY,
              "anthropic-version": "2023-06-01",
            },
            body: JSON.stringify({
              model: "claude-sonnet-4-6",
              max_tokens: 500,
              system: sys,
              messages: [{ role: "user", content: usr }],
            }),
          });

          if (res.ok) {
            const data = await res.json();
            const blocks: Array<{ type?: string; text?: string }> = Array.isArray(data?.content) ? data.content : [];
            const textBlocks = blocks.filter((b) => b?.type === "text");
            const rawText = textBlocks[textBlocks.length - 1]?.text ?? "";
            const cleaned = rawText.replace(/```json/gi, "").replace(/```/g, "").trim();
            const parsed = JSON.parse(cleaned) as { authority_ids?: unknown };
            const ids = Array.isArray(parsed.authority_ids)
              ? parsed.authority_ids.filter((i): i is string => typeof i === "string")
              : [];
            const validIds = new Set(candidates.map((c) => c.id));
            const matched = candidates.filter((c) => ids.includes(c.id) && validIds.has(c.id)).slice(0, 3);

            if (matched.length > 0) {
              const { error: insErr } = await adminSb.from("user_authority_suggestions")
                .upsert(
                  matched.map((a) => ({ question_id: questionId, authority_id: a.id, status: "suggested", suggested_by: "ai" })),
                  { onConflict: "question_id,authority_id", ignoreDuplicates: true },
                );
              if (insErr) {
                console.error(JSON.stringify({ tag: "ugq-confirm-publish.suggestion_insert_failed", message: insErr.message }));
              } else {
                suggestedAuthorities = matched;
              }
            }
          } else {
            const errBody = await res.text().catch(() => "");
            console.error(JSON.stringify({ tag: "ugq-confirm-publish.authority_llm_error", status: res.status, body: errBody.slice(0, 300) }));
          }
        }
      } catch (e) {
        console.error(JSON.stringify({ tag: "ugq-confirm-publish.authority_suggest_exception", message: (e as Error).message }));
        // Never fail the publish over this — suggestedAuthorities just stays [].
      }
    }

    // Sep 2026, NEW — see header note §5. Awaited so the Hindi rendition is
    // actually ready by the time this responds; fails open internally, so a
    // slow/failed LLM call here still lets the publish itself succeed. Also
    // a no-op whenever ugq-publish already seeded the rendition directly
    // from the proposer's own-language preview text — see that function.
    await generateRenditionsNow(SUPABASE_URL, CRON_SECRET, adminSb, questionId);

    return json(200, { ok: true, question_id: questionId, suggested_authorities: suggestedAuthorities });
  } catch (err) {
    return json(500, { ok: false, error: "INTERNAL_ERROR", message: (err as Error).message });
  }
});

// ── Cover image extraction — adapted from enrich-images/index.ts's proven
//    og:image/twitter:image scraping (same regex patterns, same Googlebot UA
//    trick, same stream-until-</head> byte cap). Deno edge functions can't
//    import across each other, hence the duplication rather than a shared
//    module — same convention already used for small pieces elsewhere in
//    this codebase. NOT mirrored to Supabase Storage (unlike enrich-images'
//    news-pipeline images) — stores the direct external URL. That's an
//    accepted, already-working state elsewhere in this schema (e.g.
//    news_items.image_url is a valid fallback whenever hosted_image_url
//    hasn't been mirrored yet), and skipping the storage round-trip keeps
//    this fast enough to run synchronously during a user-facing publish
//    click. Mirroring could be added later as a follow-up if hotlinking
//    external images becomes a problem.
//
//    Aug 2026, NOTE: this is now only exercised as a fallback — ugq-screen
//    runs the identical scrape at preview time and its result is preferred
//    above whenever present (see previewCoverImageAttempted). Kept here in
//    full (not stubbed out) so legacy preview_reframe rows written before
//    that change, and any future path that publishes without ever going
//    through ugq-screen's preview step, still get a working fallback. ──────

const IMAGE_FETCH_TIMEOUT_MS = 6000;
const IMAGE_MAX_HTML_BYTES = 50_000;
const IMAGE_USER_AGENT = "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)";

function extractMetaContent(html: string, patterns: RegExp[]): string | null {
  for (const pattern of patterns) {
    const m = html.match(pattern);
    if (m?.[1]) return m[1].trim();
  }
  return null;
}

function normalizeImageUrl(raw: string, baseUrl: string): string {
  try {
    if (raw.startsWith("//")) return "https:" + raw;
    if (raw.startsWith("/")) return new URL(raw, baseUrl).href;
    return raw.replace(/&amp;/g, "&").replace(/&#39;/g, "'");
  } catch {
    return raw;
  }
}

async function extractImageFromUrl(pageUrl: string): Promise<string | null> {
  let targetUrl: URL;
  try {
    targetUrl = new URL(pageUrl);
    if (targetUrl.protocol !== "http:" && targetUrl.protocol !== "https:") return null;
  } catch {
    return null;
  }

  let html = "";
  try {
    const controller = new AbortController();
    const timeout = setTimeout(() => controller.abort(), IMAGE_FETCH_TIMEOUT_MS);
    const res = await fetch(targetUrl.href, {
      headers: { "User-Agent": IMAGE_USER_AGENT, "Accept": "text/html" },
      signal: controller.signal,
    }).finally(() => clearTimeout(timeout));
    if (!res.ok) return null;

    const reader = res.body?.getReader();
    if (reader) {
      const decoder = new TextDecoder();
      let bytes = 0;
      while (bytes < IMAGE_MAX_HTML_BYTES) {
        const { done, value } = await reader.read();
        if (done) break;
        html += decoder.decode(value, { stream: true });
        bytes += value.length;
        if (html.includes("</head>")) break;
      }
      reader.cancel();
    } else {
      html = await res.text();
    }
  } catch {
    return null; // timeout, network error, etc. — best-effort, no image this time
  }

  const ogImage = extractMetaContent(html, [
    /property="og:image"\s+content="([^"]+)"/i,
    /content="([^"]+)"\s+property="og:image"/i,
    /property='og:image'\s+content='([^']+)'/i,
    /content='([^']+)'\s+property='og:image'/i,
  ]);
  if (ogImage) return normalizeImageUrl(ogImage, targetUrl.href);

  const twitterImage = extractMetaContent(html, [
    /name="twitter:image"\s+content="([^"]+)"/i,
    /content="([^"]+)"\s+name="twitter:image"/i,
    /name='twitter:image'\s+content='([^']+)'/i,
    /property="twitter:image"\s+content="([^"]+)"/i,
  ]);
  if (twitterImage) return normalizeImageUrl(twitterImage, targetUrl.href);

  return null;
}

// Tries up to 3 links CONCURRENTLY (not sequentially — bounds total added
// latency to ~IMAGE_FETCH_TIMEOUT_MS regardless of how many links there
// are), returns the first successful result in the ORIGINAL link order
// (i.e. deterministic preference for the search results' own ranking, not
// just whichever network response happened to land first).
async function findCoverImageFromLinks(links: string[]): Promise<string | null> {
  const candidates = links.slice(0, 3);
  if (candidates.length === 0) return null;
  try {
    const results = await Promise.allSettled(candidates.map((url) => extractImageFromUrl(url)));
    for (const r of results) {
      if (r.status === "fulfilled" && r.value) return r.value;
    }
  } catch (e) {
    console.error(JSON.stringify({ tag: "ugq-confirm-publish.cover_image_exception", message: (e as Error).message }));
  }
  return null;
}
