// src/components/question/QuestionStanceSlider.tsx
// OPTIMIZED: Instant feedback with debounced AI calls
// DESIGN PASS 2: Gradient spectrum track, micro-commitment prompt, pulseThumb prop,
//   stats prop wired for personalized alignment messaging in parent
// COPY UPDATE: Decision-oriented pre-commit prompts for hero/featured (pulseThumb=true)
//   Hero:     "Do you support or oppose this?" + "Choose a position in seconds."
//   Featured: same (pulseThumb=true from Index)
//   Grid:     "Move the slider to express your view." (unchanged)
//   Header label: "Your position" for prominent, "Your stance" for small
// M-M01: ARIA attributes added to Slider for screen-reader compliance

import * as React from "react";
import { useQuery } from "@tanstack/react-query";
import { Slider } from "@/components/ui/slider";
import { cn } from "@/lib/utils";
import { getSupabase } from "@/lib/supabaseClient";
import { getStanceColorHex, buildStanceLabels } from "@/lib/stanceColors";

// RegionalStat type — mirrored from QuestionDetailPage to avoid cross-import
type RegionalStat = {
  region_scope: string;
  region_label: string;
  total_responses: number;
  pct_agree: number | null;
  pct_disagree: number | null;
  pct_neutral: number | null;
  avg_score: number | null;
};

type QuestionStats = {
  my_stance: number | null;
  location: {
    city: string | null;
    county: string | null;
    state: string | null;
    country: string | null;
  } | null;
  regions: {
    global?: RegionalStat | null;
    city?: RegionalStat | null;
    county?: RegionalStat | null;
    state?: RegionalStat | null;
    country?: RegionalStat | null;
    [key: string]: RegionalStat | null | undefined;
  } | null;
};

export type QuestionStanceSliderProps = {
  questionId: string;
  questionText?: string | null;
  summary?: string | null;
  initialValue: number | null; // -2..2 or null
  onSubmit?: (value: number) => Promise<void> | void;
  disabled?: boolean;
  // Point 16: stats passed from parent for personalized alignment messaging
  stats?: QuestionStats | null;
  // Point 17: pulse thumb + decision-oriented copy for hero/featured slots
  pulseThumb?: boolean;
  // When true, the prop-sync effect is suppressed so an in-flight save
  // does not snap the slider back to the stale server value mid-drag.
  mutationPending?: boolean;
  // Fires once on first meaningful slider interaction (guest engagement signal).
  // Used by HeroSection to transition the right panel from locked → engaged.
  // Only passed in the guest hero context — optional, never called on authed path.
  onInteractionStart?: () => void;
  // Dynamic slider endpoint labels generated by the reframe pipeline.
  // Describe what the oppose/support ends of the spectrum mean for this
  // specific question. Falls back to generic labels when null.
  sliderLowLabel?: string | null;
  sliderHighLabel?: string | null;
  // Optional element rendered inline with the pre-commit heading (e.g. a
  // compact ShareButton). Opt-in only — omitted everywhere except where a
  // caller explicitly passes it, so existing usages are unaffected.
  headerAction?: React.ReactNode;
};

// Oppose/support framing matches the pre-commit prompt ("Do you support or oppose this?")
// and is meaningful for both binary propositions and multi-axis trade-off questions,
// where "agree/disagree" has no clear referent.
const STANCE_LABELS: Record<number, string> = {
  [-2]: "Strongly oppose",
  [-1]: "Lean oppose",
  [0]: "Neutral",
  [1]: "Lean support",
  [2]: "Strongly support",
};

const STANCE_TIPS_FALLBACK: Record<number, string> = {
  [-2]:
    "You strongly oppose this. You would prefer alternatives that avoid these trade-offs entirely.",
  [-1]:
    "You lean toward opposing this. You see more downsides than upsides, but might accept it with significant changes.",
  [0]:
    "You're neutral or unsure. You may see valid points on multiple sides or need more information to decide.",
  [1]:
    "You lean toward supporting this. You believe the benefits outweigh the costs, with some reservations.",
  [2]:
    "You strongly support this. You accept the trade-offs as worthwhile to achieve the intended outcome.",
};


function clampStance(val: number | null | undefined): number {
  if (typeof val !== "number" || !Number.isFinite(val)) return 0;
  return Math.max(-2, Math.min(2, Math.round(val)));
}

// ---------- Helpers ----------

function getMajorityStance(
  r: RegionalStat | null | undefined
): "agree" | "disagree" | "neutral" | null {
  if (!r) return null;
  const { pct_agree, pct_disagree, pct_neutral } = r;
  if (pct_agree == null && pct_disagree == null && pct_neutral == null)
    return null;
  const a = pct_agree ?? 0;
  const d = pct_disagree ?? 0;
  const n = pct_neutral ?? 0;
  if (a >= d && a >= n) return "agree";
  if (d >= a && d >= n) return "disagree";
  return "neutral";
}

function stanceToCategory(val: number): "agree" | "disagree" | "neutral" {
  if (val > 0) return "agree";
  if (val < 0) return "disagree";
  return "neutral";
}

// Debounced AI tip hook — only calls AI after user stops moving slider
function useDebouncedAiStanceTip(
  questionId: string,
  stance: number,
  questionText?: string | null,
  summary?: string | null,
  lowLabel?: string | null,
  highLabel?: string | null
) {
  const supabase = getSupabase()!;
  const [debouncedStance, setDebouncedStance] = React.useState(stance);

  React.useEffect(() => {
    const timer = setTimeout(() => {
      setDebouncedStance(stance);
    }, 500);
    return () => clearTimeout(timer);
  }, [stance]);

  return useQuery({
    queryKey: ["ai-stance-tip", questionId, debouncedStance, questionText, summary, lowLabel, highLabel],
    enabled: !!questionId && Number.isFinite(debouncedStance),
    staleTime: 10 * 60_000,
    queryFn: async () => {
      const { data, error } = await supabase.functions.invoke("ai-stance-tip", {
        body: {
          question_id: questionId,
          stance: debouncedStance,
          question_text: questionText ?? null,
          summary: summary ?? null,
          low_label: lowLabel ?? null,
          high_label: highLabel ?? null,
        },
      });

      if (error) {
        console.warn(
          "[QuestionStanceSlider] ai-stance-tip error; using fallback",
          error
        );
        return {
          tip: null as string | null,
          source: "fallback" as const,
          reason: "invoke_error" as const,
        };
      }

      const raw = data as any;
      const tipText =
        raw && typeof raw.tip === "string" ? (raw.tip as string).trim() : null;
      const source =
        raw && raw.source === "ai" ? ("ai" as const) : ("fallback" as const);
      const reason = raw?.reason ?? null;

      console.info("[QuestionStanceSlider] ai-stance-tip result", {
        stance: debouncedStance,
        source,
        reason,
        tip: tipText,
      });

      return { tip: tipText, source, reason };
    },
  });
}

// ---- Component ----
export function QuestionStanceSlider({
  questionId,
  questionText,
  summary,
  initialValue,
  onSubmit,
  disabled,
  stats,
  pulseThumb,
  mutationPending = false,
  onInteractionStart,
  sliderLowLabel,
  sliderHighLabel,
  headerAction,
}: QuestionStanceSliderProps) {
  const [value, setValue] = React.useState<number>(clampStance(initialValue));
  const [committed, setCommitted] = React.useState(
    typeof initialValue === "number" && initialValue !== null
  );
  // Keep local slider state aligned with the parent/server truth.
  // Without this, the slider can keep showing the last dragged value
  // while surrounding QDP UI reflects a different saved stance.
  //
  // Guard: do NOT sync while a mutation is in-flight. If a React Query
  // refetch resolves during the save (e.g. triggered by the realtime channel),
  // initialValue changes to the *old* value and this effect would snap the
  // slider back to the stale position while "Saving…" is still showing.
  React.useEffect(() => {
    if (mutationPending) return;
    if (typeof initialValue === "number" && initialValue !== null) {
      setValue(clampStance(initialValue));
      setCommitted(true);
    } else {
      setValue(0);
      setCommitted(false);
    }
  }, [initialValue, questionId, mutationPending]);

  const { data: aiData, isLoading: aiLoading } = useDebouncedAiStanceTip(
    questionId,
    value,
    questionText,
    summary,
    sliderLowLabel,
    sliderHighLabel
  );

  const stanceLabels = buildStanceLabels(sliderLowLabel, sliderHighLabel);
  const label = stanceLabels[value] ?? "Select stance";
  const fallbackTip = STANCE_TIPS_FALLBACK[value] ?? "";
  const tip = aiData?.tip || fallbackTip;

  // Ref guard: fires onInteractionStart exactly once per mount.
  // The slider remounts on question change (key prop), so this resets naturally.
  const hasFiredInteractionRef = React.useRef(false);

  const handleChange = (vals: number[]) => {
    if (!hasFiredInteractionRef.current) {
      hasFiredInteractionRef.current = true;
      onInteractionStart?.();
    }
    const v = clampStance(vals[0] ?? 0);
    setValue(v);
  };

  // Keep onSubmit in a ref so the commit handler always calls the latest version
  // without needing it as a dependency.
  const onSubmitRef = React.useRef(onSubmit);
  React.useEffect(() => {
    onSubmitRef.current = onSubmit;
  }, [onSubmit]);

  // Submit directly on commit.
  // Radix onValueCommit must stay synchronous, but invoking mutate() through the
  // parent callback is safe here because the call itself is synchronous.
  const handleCommit = (vals: number[]) => {
    const v = clampStance(vals[0] ?? 0);
    setValue(v);
    setCommitted(true);

    if (!onSubmitRef.current) return;

    // Avoid resubmitting when the committed position already matches
    // the latest parent-provided saved stance.
    if (typeof initialValue === "number" && clampStance(initialValue) === v) {
      return;
    }

    void Promise.resolve(onSubmitRef.current(v));
  };

  const stanceColor = getStanceColorHex(value);
  const rawPercent = ((value + 2) / 4) * 100;
  const fillPercent = Math.max(8, rawPercent);

  // ---------- Point 18: Personalized alignment messaging ----------
  const userCategory = stanceToCategory(value);
  const globalRegion = stats?.regions?.global ?? null;
  const countryRegion = stats?.regions?.country ?? null;
  const stateRegion = stats?.regions?.state ?? null;
  const locationState = stats?.location?.state ?? null;
  const locationCountry = stats?.location?.country ?? null;

  type AlignmentLine = { label: string; pct: number; aligns: boolean };
  const alignmentLines: AlignmentLine[] = [];

  function buildLine(
    r: RegionalStat | null | undefined,
    regionLabel: string
  ): AlignmentLine | null {
    if (!r) return null;
    const pct =
      userCategory === "agree"
        ? r.pct_agree
        : userCategory === "disagree"
        ? r.pct_disagree
        : r.pct_neutral;
    if (pct == null) return null;
    const majority = getMajorityStance(r);
    return {
      label: regionLabel,
      pct: Math.round(pct),
      aligns: majority === userCategory,
    };
  }

  const globalLine = buildLine(globalRegion, "globally");
  const countryLine = buildLine(countryRegion, locationCountry ?? "your country");
  const stateLine = buildLine(stateRegion, locationState ?? "your state");

  if (globalLine) alignmentLines.push(globalLine);
  if (countryLine) alignmentLines.push(countryLine);
  if (stateLine) alignmentLines.push(stateLine);

  const isFirstRespondent = committed && (stats?.total_responses ?? 0) <= 1;
  const showAlignment = committed && alignmentLines.length > 0 && !isFirstRespondent;

  // Hero/featured: pulseThumb=true → decision-oriented copy
  // Small grid cards: pulseThumb=false/undefined → lighter UI-hint copy
  const isProminent = !!pulseThumb;

  return (
    <div className="w-full space-y-3">

      {/* Pre-commit prompt — decision-first framing for hero/featured */}
      {!committed && (
        isProminent ? (
          <div className="flex items-start justify-between gap-2">
            <div>
              <p className="text-sm font-semibold text-slate-800">
                Do you support or oppose this?
              </p>
              <p className="text-[11px] text-slate-400 mt-0.5">
                Choose a position in seconds.
              </p>
            </div>
            {headerAction}
          </div>
        ) : (
          <p className="text-[11px] text-slate-500">
            Move the slider to express your view.
          </p>
        )
      )}

      {/* Header label */}
      <div className="flex items-center justify-between text-[11px] text-slate-600">
        <span className="font-semibold uppercase tracking-wide">
          {isProminent ? "Your position" : "Your stance"}
        </span>
        <span className="font-semibold text-slate-900">{label}</span>
      </div>

      {/* Slider — M-M01: ARIA labelled group with valuetext */}
      <div
        className="space-y-1"
        role="group"
        aria-labelledby="stance-slider-label"
      >
        <span id="stance-slider-label" className="sr-only">
          Stance slider — move left to oppose, right to support
        </span>

        <div className="relative py-2 sm:py-1 touch-pan-x">
          {/* Gradient track — decorative */}
          <div
            className="pointer-events-none absolute inset-x-0 top-1/2 -translate-y-1/2 rounded-full"
            style={{ height: "12px" }}
            aria-hidden
          >
            <div
              className="h-full w-full rounded-full"
              style={{
                background:
                  "linear-gradient(to right, rgba(248,113,113,0.15), rgba(203,213,225,0.15), rgba(74,222,128,0.15))",
              }}
            />
          </div>

          <Slider
            min={-2}
            max={2}
            step={1}
            value={[value]}
            disabled={disabled}
            onValueChange={handleChange}
            onValueCommit={handleCommit}
            className="relative w-full"
            aria-label="Stance"
            aria-valuemin={-2}
            aria-valuemax={2}
            aria-valuenow={value}
            aria-valuetext={stanceLabels[value] ?? "Neutral"}
          />

          {/* Colored fill — decorative */}
          <div
            className="pointer-events-none absolute inset-x-0 top-1/2 -translate-y-1/2 rounded-full bg-slate-200"
            style={{ height: "12px" }}
            aria-hidden
          >
            <div
              className={cn(
                "h-full rounded-full transition-[width,background-color] duration-300"
              )}
              style={{
                width: `${fillPercent}%`,
                backgroundColor: stanceColor,
                opacity: 0.85,
              }}
            />
          </div>

          {/* Pulse overlay — decorative */}
          {!committed && !disabled && (
            <div
              className="pointer-events-none absolute top-1/2 -translate-y-1/2 -translate-x-1/2"
              style={{ left: `${fillPercent}%` }}
              aria-hidden
            >
              <div className="h-5 w-5 rounded-full bg-slate-400/20 animate-ping" />
            </div>
          )}
        </div>

        {/* Tick labels — 5 positions across the track.
             ±2 use dynamic endpoint labels when available; ±1 are derived
             ("Lean toward X") from the endpoint labels on wider viewports.
             aria-hidden since aria-valuetext on the Slider carries the meaning. */}
        <div
          className="flex justify-between text-[11px] text-slate-500"
          aria-hidden
        >
          {/* -2 */}
          <span className="max-w-[72px] leading-tight shrink-0 overflow-hidden line-clamp-3 break-words text-[10px]">
            {stanceLabels[-2]}
          </span>
          {/* -1: hidden on mobile to avoid crowding */}
          <span className="hidden max-w-[100px] leading-tight text-center shrink-0 text-slate-400">
            {stanceLabels[-1]}
          </span>
          {/* 0 */}
          <span className="shrink-0">Neutral</span>
          {/* +1: hidden on mobile */}
          <span className="hidden max-w-[100px] leading-tight text-center shrink-0 text-slate-400">
            {stanceLabels[1]}
          </span>
          {/* +2 */}
          <span className="max-w-[72px] text-right leading-tight shrink-0 overflow-hidden line-clamp-3 break-words text-[10px]">
            {stanceLabels[2]}
          </span>
        </div>

        <div className="block sm:hidden text-[10px] text-slate-400 mt-0.5">
          Swipe or drag the slider to adjust your stance.
        </div>
      </div>

      {/* Tip box */}
      <div className="rounded-md border bg-slate-50 px-3 py-2 text-[11px] text-slate-700 min-h-[52px]">
        <div className="flex items-center justify-between mb-0.5">
          <div className="font-semibold">What this stance means</div>
          {aiLoading && (
            <div className="text-[9px] text-slate-400 animate-pulse">
              Loading AI tip...
            </div>
          )}
        </div>
        <p
          className={cn(
            "transition-opacity duration-200",
            aiLoading && "opacity-50"
          )}
        >
          {tip}
        </p>
      </div>

      {/*
       * Point 18: Personalized alignment messaging — shown after stance committed.
       * Only renders when stats are available.
       */}
      {isFirstRespondent && (
        <div className="rounded-md border border-slate-200 bg-white px-3 py-2.5 text-[11px] space-y-1.5">
          <div className="font-semibold text-slate-700">
            You chose: <span className="text-slate-900">{label}</span>
          </div>
          <div className="text-slate-500 leading-relaxed">
            You&#x2019;re the first to weigh in on this. We&#x2019;ll show you how others compare once more stances come in.
          </div>
        </div>
      )}
      {showAlignment && (
        <div className="rounded-md border border-slate-200 bg-white px-3 py-2.5 text-[11px] space-y-1.5">
          <div className="font-semibold text-slate-700">
            You chose: <span className="text-slate-900">{label}</span>
          </div>
          <div className="space-y-1">
            {alignmentLines.map((line) => (
              <div key={line.label} className="text-slate-600">
                <span className="font-medium text-slate-800">{line.pct}%</span>
                {" of "}
                <span className="capitalize">{line.label}</span>
                {" "}
                <span className={line.aligns ? "text-slate-700" : "text-slate-500"}>
                  {line.aligns ? "agrees" : "disagrees"}
                </span>
                {" with you"}
              </div>
            ))}
          </div>
        </div>
      )}

      {disabled && (
        <div className="flex items-center gap-1.5 text-[10px] text-slate-400">
          <div className="h-1.5 w-1.5 rounded-full bg-slate-300 animate-pulse" />
          Saving…
        </div>
      )}
    </div>
  );
}
