-- Epic UGQ (Aug 2026): store a fast, unverified "preview" reframe generated
-- alongside Gate 1 screening, so proposers see roughly how their raw text
-- might read as a polished stance question immediately on submit — before
-- admin review and before the fact-checked pipeline (reframe_result) runs.
-- Distinct from reframe_result (admin-triggered, fact-checked, Stage A/B/C).
ALTER TABLE public.user_question_proposals
  ADD COLUMN IF NOT EXISTS preview_reframe jsonb;

COMMENT ON COLUMN public.user_question_proposals.preview_reframe IS
  'Fast, unverified preview reframe generated by ugq-screen at submit time (Gate 1). Shape: {question, slider_low_label, slider_high_label, quality_notes, model, generated_at}. NOT fact-checked — distinct from reframe_result, which is the admin-triggered, fact-checked Stage A/B/C output in ugq-moderate.';
