-- Epic Report R3 — capture WHY a respondent chose their position.
--
-- Without this, the report's "why" can only describe what each position
-- stands for (question_stance_definitions). R3 records respondents' own
-- reasons right after they vote: one-tap options for the side they chose,
-- plus an optional one-line "why?".
--
--   question_reason_options          the 3-4 tap options per side, per QUESTION
--                                    (not per rendition, so tallies survive a
--                                    translation or a republish), generated by
--                                    the generate-reason-options edge function
--   question_reason_option_labels    each option's label per language
--   question_stance_reasons          a signed-in respondent's reason (one per
--                                    user + question; latest wins)
--   question_stance_reasons_pending  an anonymous respondent's reason, keyed by
--                                    device like question_stances_pending, and
--                                    moved over on sign-in by
--                                    commit_staged_reasons_for_device_by_user
--
-- Free text is written with moderation_status 'pending' and scored by the
-- submit-stance-reason edge function (OpenAI moderation + a PII pattern
-- check). Only 'clean' text is ever quotable; anything else still counts in
-- the option tallies but is never shown.
--
-- A reason is tied to the SIDE of the score it was given with. If the
-- respondent later moves to the other side, the old reason stops counting
-- (the report only counts reasons whose side matches the current answer).

create or replace function public.stance_side(p_score integer)
returns text
language sql
immutable
as $$
  select case when p_score < 0 then 'low' when p_score > 0 then 'high' else 'neutral' end;
$$;

-- ---------------------------------------------------------------------------
-- Options
-- ---------------------------------------------------------------------------
create table if not exists public.question_reason_options (
  id                  uuid primary key default gen_random_uuid(),
  question_id         uuid not null references public.questions(id) on delete cascade,
  source_rendition_id uuid references public.question_renditions(id) on delete set null,
  side                text not null check (side in ('low', 'neutral', 'high')),
  option_key          text not null check (option_key ~ '^[a-z0-9_]{2,40}$'),
  position            smallint not null default 0,
  model               text,
  prompt_version      text,
  created_at          timestamptz not null default now(),
  unique (question_id, option_key)
);
create index if not exists question_reason_options_question_idx
  on public.question_reason_options (question_id, side, position);

create table if not exists public.question_reason_option_labels (
  option_id     uuid not null references public.question_reason_options(id) on delete cascade,
  language_code text not null,
  label         text not null check (char_length(label) between 2 and 120),
  created_at    timestamptz not null default now(),
  primary key (option_id, language_code)
);

alter table public.question_reason_options enable row level security;
alter table public.question_reason_option_labels enable row level security;
drop policy if exists qro_public_read on public.question_reason_options;
create policy qro_public_read on public.question_reason_options for select using (true);
drop policy if exists qrol_public_read on public.question_reason_option_labels;
create policy qrol_public_read on public.question_reason_option_labels for select using (true);
grant select on public.question_reason_options, public.question_reason_option_labels to anon, authenticated;

-- ---------------------------------------------------------------------------
-- Reasons
-- ---------------------------------------------------------------------------
create table if not exists public.question_stance_reasons (
  id                uuid primary key default gen_random_uuid(),
  user_id           uuid not null references auth.users(id) on delete cascade,
  question_id       uuid not null references public.questions(id) on delete cascade,
  rendition_id      uuid references public.question_renditions(id) on delete set null,
  score_at_time     smallint not null check (score_at_time between -2 and 2),
  option_keys       text[] not null default '{}',
  reason_text       text check (reason_text is null or char_length(reason_text) <= 280),
  language_code     text,
  source            text not null default 'native',
  moderation_status text not null default 'none'
                    check (moderation_status in ('none', 'pending', 'clean', 'flagged', 'pii', 'error')),
  moderation_score  numeric,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now(),
  unique (user_id, question_id)
);
create index if not exists question_stance_reasons_question_idx
  on public.question_stance_reasons (question_id);

create table if not exists public.question_stance_reasons_pending (
  id                  uuid primary key default gen_random_uuid(),
  question_id         uuid not null references public.questions(id) on delete cascade,
  responder_device_id text not null,
  forward_chain_id    text,
  rendition_id        uuid references public.question_renditions(id) on delete set null,
  score_at_time       smallint not null check (score_at_time between -2 and 2),
  option_keys         text[] not null default '{}',
  reason_text         text check (reason_text is null or char_length(reason_text) <= 280),
  language_code       text,
  moderation_status   text not null default 'none'
                      check (moderation_status in ('none', 'pending', 'clean', 'flagged', 'pii', 'error')),
  moderation_score    numeric,
  committed           boolean not null default false,
  committed_at        timestamptz,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now(),
  unique (responder_device_id, question_id)
);
create index if not exists question_stance_reasons_pending_question_idx
  on public.question_stance_reasons_pending (question_id);

alter table public.question_stance_reasons enable row level security;
alter table public.question_stance_reasons_pending enable row level security;

-- A signed-in user can read their own reason (so the prompt can tell it has
-- already been answered on another device). Nobody reads anyone else's;
-- the report only ever sees aggregates through its SECURITY DEFINER RPC.
drop policy if exists qsr_select_own on public.question_stance_reasons;
create policy qsr_select_own on public.question_stance_reasons
  for select using (user_id = auth.uid());
grant select on public.question_stance_reasons to authenticated;
-- question_stance_reasons_pending: no policies, no grants — definer RPCs only.

-- Keep only option keys that exist for this question AND this side; at most 4.
create or replace function public._valid_reason_keys(p_question_id uuid, p_side text, p_keys text[])
returns text[]
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(array_agg(o.option_key order by o.position), '{}')
  from (select distinct k from unnest(coalesce(p_keys, '{}')) k) ks
  join public.question_reason_options o
    on o.question_id = p_question_id and o.side = p_side and o.option_key = ks.k;
$$;
revoke all on function public._valid_reason_keys(uuid, text, text[]) from public, anon, authenticated;

-- ---------------------------------------------------------------------------
-- Save: signed-in
-- ---------------------------------------------------------------------------
create or replace function public.set_my_stance_reason(
  p_question_id   uuid,
  p_option_keys   text[],
  p_text          text,
  p_language_code text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid    uuid := auth.uid();
  v_score  smallint;
  v_rend   uuid;
  v_source text;
  v_keys   text[];
  v_text   text := nullif(btrim(coalesce(p_text, '')), '');
  v_id     uuid;
  v_status text;
begin
  if v_uid is null then
    raise exception 'not_signed_in' using errcode = '42501';
  end if;
  select s.score, s.rendition_id, coalesce(s.source, 'native')
    into v_score, v_rend, v_source
    from public.question_stances s
   where s.user_id = v_uid and s.question_id = p_question_id;
  if not found then
    raise exception 'no_stance' using errcode = '42501';
  end if;

  v_keys := public._valid_reason_keys(p_question_id, public.stance_side(v_score), p_option_keys);
  v_keys := v_keys[1:4];
  v_text := left(v_text, 280);
  if coalesce(cardinality(v_keys), 0) = 0 and v_text is null then
    raise exception 'empty_reason' using errcode = '22023';
  end if;
  v_status := case when v_text is null then 'none' else 'pending' end;

  insert into public.question_stance_reasons as r
    (user_id, question_id, rendition_id, score_at_time, option_keys, reason_text,
     language_code, source, moderation_status, moderation_score)
  values
    (v_uid, p_question_id, v_rend, v_score, v_keys, v_text,
     nullif(p_language_code, ''), v_source, v_status, null)
  on conflict (user_id, question_id) do update
     set rendition_id      = excluded.rendition_id,
         score_at_time     = excluded.score_at_time,
         option_keys       = excluded.option_keys,
         reason_text       = excluded.reason_text,
         language_code     = excluded.language_code,
         source            = excluded.source,
         moderation_status = excluded.moderation_status,
         moderation_score  = null,
         updated_at        = now()
  returning r.id into v_id;

  return jsonb_build_object('id', v_id, 'kind', 'signed_in', 'moderation_status', v_status, 'option_keys', v_keys);
end;
$$;
revoke all on function public.set_my_stance_reason(uuid, text[], text, text) from public, anon;
grant execute on function public.set_my_stance_reason(uuid, text[], text, text) to authenticated;

-- ---------------------------------------------------------------------------
-- Save: anonymous (same trust model as record_web_stance — the device id is
-- a random client-held secret; a reason can only attach to an uncommitted
-- pending answer from that device).
-- ---------------------------------------------------------------------------
create or replace function public.record_web_stance_reason(
  p_question_id   uuid,
  p_device_id     text,
  p_option_keys   text[],
  p_text          text,
  p_language_code text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_score smallint;
  v_rend  uuid;
  v_chain text;
  v_keys  text[];
  v_text  text := nullif(btrim(coalesce(p_text, '')), '');
  v_id    uuid;
  v_status text;
begin
  if p_device_id is null or p_device_id !~ '^dev_[A-Za-z0-9]{6,40}$' then
    raise exception 'invalid_device' using errcode = '22023';
  end if;
  select qsp.score, qsp.rendition_id, qsp.forward_chain_id
    into v_score, v_rend, v_chain
    from public.question_stances_pending qsp
    left join public.whatsapp_forward_chains w on w.id = qsp.forward_chain_id
   where qsp.question_id = p_question_id
     and coalesce(qsp.committed, false) = false
     and (qsp.responder_device_id = p_device_id or w.responder_device_id = p_device_id)
   order by qsp.updated_at desc
   limit 1;
  if not found then
    raise exception 'no_stance' using errcode = '42501';
  end if;

  v_keys := public._valid_reason_keys(p_question_id, public.stance_side(v_score), p_option_keys);
  v_keys := v_keys[1:4];
  v_text := left(v_text, 280);
  if coalesce(cardinality(v_keys), 0) = 0 and v_text is null then
    raise exception 'empty_reason' using errcode = '22023';
  end if;
  v_status := case when v_text is null then 'none' else 'pending' end;

  insert into public.question_stance_reasons_pending as r
    (question_id, responder_device_id, forward_chain_id, rendition_id, score_at_time,
     option_keys, reason_text, language_code, moderation_status)
  values
    (p_question_id, p_device_id, v_chain, v_rend, v_score,
     v_keys, v_text, nullif(p_language_code, ''), v_status)
  on conflict (responder_device_id, question_id) do update
     set forward_chain_id  = excluded.forward_chain_id,
         rendition_id      = excluded.rendition_id,
         score_at_time     = excluded.score_at_time,
         option_keys       = excluded.option_keys,
         reason_text       = excluded.reason_text,
         language_code     = excluded.language_code,
         moderation_status = excluded.moderation_status,
         moderation_score  = null,
         committed         = false,
         committed_at      = null,
         updated_at        = now()
  returning r.id into v_id;

  return jsonb_build_object('id', v_id, 'kind', 'anonymous', 'moderation_status', v_status, 'option_keys', v_keys);
end;
$$;
grant execute on function public.record_web_stance_reason(uuid, text, text[], text, text) to anon, authenticated;

-- ---------------------------------------------------------------------------
-- Commit on sign-in. Called right after commit_staged_stances_for_device_by_user
-- on every sign-in path, with the same device ids. Only moves a reason whose
-- stance is now the user's committed stance; never overwrites a reason the
-- user saved later while signed in.
-- ---------------------------------------------------------------------------
create or replace function public.commit_staged_reasons_for_device_by_user(p_device_id text, p_user_id uuid)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_count integer := 0;
  r record;
begin
  if not (auth.uid() = p_user_id or coalesce(auth.jwt() ->> 'role', '') = 'service_role') then
    raise exception 'Not authorized' using errcode = '42501';
  end if;
  if p_device_id is null or p_device_id = '' then
    return 0;
  end if;

  for r in
    select pr.*
      from public.question_stance_reasons_pending pr
     where pr.responder_device_id = p_device_id
       and pr.committed = false
  loop
    -- The stance must already be the user's (committed a moment earlier by
    -- commit_staged_stances_for_device_by_user); otherwise leave it pending.
    if exists (select 1 from public.question_stances s
                where s.user_id = p_user_id and s.question_id = r.question_id) then
      insert into public.question_stance_reasons as q
        (user_id, question_id, rendition_id, score_at_time, option_keys, reason_text,
         language_code, source, moderation_status, moderation_score, created_at, updated_at)
      values
        (p_user_id, r.question_id, r.rendition_id, r.score_at_time, r.option_keys, r.reason_text,
         r.language_code, 'web_forward', r.moderation_status, r.moderation_score, r.created_at, r.updated_at)
      on conflict (user_id, question_id) do update
         set rendition_id      = excluded.rendition_id,
             score_at_time     = excluded.score_at_time,
             option_keys       = excluded.option_keys,
             reason_text       = excluded.reason_text,
             language_code     = excluded.language_code,
             moderation_status = excluded.moderation_status,
             moderation_score  = excluded.moderation_score,
             updated_at        = excluded.updated_at
       where q.updated_at < excluded.updated_at;

      update public.question_stance_reasons_pending
         set committed = true, committed_at = now()
       where id = r.id;
      v_count := v_count + 1;
    end if;
  end loop;

  return v_count;
end;
$$;
revoke all on function public.commit_staged_reasons_for_device_by_user(text, uuid) from public, anon;
grant execute on function public.commit_staged_reasons_for_device_by_user(text, uuid) to authenticated, service_role;

-- ---------------------------------------------------------------------------
-- Report: reason tallies. Replaces the 'reasons', null placeholder in
-- get_question_insight_report. Only reasons from respondents the report
-- already counts, and only while the reason's side matches their current
-- answer. Quotes: moderation 'clean' only, at most 3 per side, and only when
-- that side has at least 5 respondents who gave a reason (decision D8).
-- ---------------------------------------------------------------------------
do $mig$
declare src text; newsrc text;
begin
  select prosrc into src from pg_proc where proname = 'get_question_insight_report';
  newsrc := replace(src,
$a$    'reasons', null$a$,
$b$    'reasons', (
      with rs as (
        select public.stance_side(r.score_at_time) as side, r.option_keys, r.reason_text,
               r.moderation_status, r.updated_at
          from public.question_stance_reasons r
          join public.question_stances s
            on s.user_id = r.user_id and s.question_id = r.question_id
         where r.question_id = p_question_id
           and coalesce(s.is_flagged, false) = false
           and public.stance_counts_toward_aggregate(s.rendition_id)
           and public.stance_side(s.score) = public.stance_side(r.score_at_time)
        union all
        select public.stance_side(pr.score_at_time), pr.option_keys, pr.reason_text,
               pr.moderation_status, pr.updated_at
          from public.question_stance_reasons_pending pr
         where pr.question_id = p_question_id
           and pr.committed = false
           and exists (
             select 1 from public.question_stances_pending ps
              where ps.question_id = pr.question_id
                and coalesce(ps.committed, false) = false
                and (ps.responder_device_id = pr.responder_device_id
                     or ps.forward_chain_id = pr.forward_chain_id)
                and public.stance_counts_toward_aggregate(ps.rendition_id)
                and public.stance_side(ps.score) = public.stance_side(pr.score_at_time))
      )
      select jsonb_build_object(
        'totalWithReasons', (select count(*) from rs)::int,
        'freeText', (select count(*) from rs where rs.reason_text is not null)::int,
        'sides', (
          select jsonb_agg(jsonb_build_object(
                   'side', sd.side,
                   'respondents', (select count(*) from rs where rs.side = sd.side)::int,
                   'options', (
                     select coalesce(jsonb_agg(jsonb_build_object(
                              'key', o.option_key,
                              'label', coalesce(lv.label, le.label, o.option_key),
                              'count', (select count(*) from rs
                                         where rs.side = sd.side and o.option_key = any(rs.option_keys))::int)
                              order by o.position), '[]'::jsonb)
                       from public.question_reason_options o
                       left join public.question_reason_option_labels lv
                         on lv.option_id = o.id and lv.language_code = v_lang
                       left join public.question_reason_option_labels le
                         on le.option_id = o.id and le.language_code = 'en'
                      where o.question_id = p_question_id and o.side = sd.side),
                   'quotes', case
                     when (select count(*) from rs where rs.side = sd.side) >= 5 then (
                       select coalesce(jsonb_agg(q.reason_text), '[]'::jsonb)
                         from (select rs.reason_text from rs
                                where rs.side = sd.side
                                  and rs.moderation_status = 'clean'
                                  and char_length(rs.reason_text) >= 10
                                order by rs.updated_at desc
                                limit 3) q)
                     else '[]'::jsonb end)
                 order by sd.ord)
            from (values ('high', 1), ('neutral', 2), ('low', 3)) sd(side, ord))
      )
    )$b$);
  if newsrc = src then raise exception 'reasons placeholder not found'; end if;
  execute format($f$create or replace function public.get_question_insight_report(p_question_id uuid, p_language text default 'en')
    returns jsonb language plpgsql stable security definer set search_path = public as %L$f$, newsrc);
end $mig$;
