// supabase/functions/classify-topic-drafts/index.ts
//
// Two-phase operation — works directly on the TOPICS table:
//
//   Phase 1 — Bootstrap (runs when < MIN_PARENTS exist)
//     Sends orphan topic titles to GPT-4o → generates 8-15 broad parent categories
//     → inserts them into topics as root rows (parent_topic_id = null)
//
//   Phase 2 — Classify (always runs)
//     For each orphan topic row (parent_topic_id IS NULL, not itself a parent),
//     asks GPT-4o-mini which parent fits best.
//     Writes parent_topic_id directly onto the topics row.
//
// NOTE: Works on `topics` table directly — not topic_drafts.
// topics.draft_id → ai_question_drafts (not topic_drafts) for most rows,
// so classifying topic_drafts was the wrong table.
//
// Auth: JWT decoded → is_admin(uid) via service role.
// Env:  SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, OPENAI_API_KEY
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.45.2";
import OpenAI from "https://esm.sh/openai@4.57.0";
function log(level, msg, extra = {}) {
  console.log(JSON.stringify({
    ts: new Date().toISOString(),
    level,
    func: "classify-topic-drafts",
    msg,
    ...extra
  }));
}
const CORS_HEADERS = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
  "Access-Control-Allow-Headers": "Authorization, Content-Type, x-client-info, apikey"
};
function json(data, status = 200) {
  return new Response(JSON.stringify(data), {
    status,
    headers: {
      "content-type": "application/json",
      ...CORS_HEADERS
    }
  });
}
// ─── Phase 1: Bootstrap parent topics from orphan topic titles ────────────────
const BOOTSTRAP_SYSTEM = `You are a news taxonomy designer.
Given a list of news topic titles, identify 8 to 15 broad parent categories
that together cover all the topics. Each category should be:
- Broad enough to cover multiple related topics (not a single news story)
- Specific enough to be meaningful (not just "Politics" or "World News")
- Mutually exclusive where possible

Return ONLY valid JSON:
{
  "categories": [
    { "title": "Category Name", "tags": ["tag1", "tag2", "tag3"] },
    ...
  ]
}

Good examples:
- "Middle East Conflict" (tags: iran, israel, conflict, geopolitics)
- "US Domestic Policy" (tags: congress, legislation, federal)
- "Technology & AI" (tags: ai, tech, software)
- "Global Finance" (tags: economy, markets, banking)
- "Climate & Environment" (tags: climate, energy, environment)
- "Sports & Athletics" (tags: sports, nfl, nba, football)
- "Military & Defense" (tags: military, defense, nato)
- "Public Health" (tags: health, medical, disease)`;
async function bootstrapParentTopics(orphans, db, openai) {
  log("info", "bootstrap.start", {
    orphan_count: orphans.length
  });
  const titleList = orphans.filter((t)=>t.title).map((t, i)=>`${i + 1}. ${t.title}`).join("\n");
  const completion = await openai.chat.completions.create({
    model: "gpt-4o",
    temperature: 0.3,
    max_tokens: 1000,
    response_format: {
      type: "json_object"
    },
    messages: [
      {
        role: "system",
        content: BOOTSTRAP_SYSTEM
      },
      {
        role: "user",
        content: `Here are ${orphans.length} news topic titles. Generate broad parent categories:\n\n${titleList}`
      }
    ]
  });
  const raw = completion.choices[0]?.message?.content?.trim() ?? "{}";
  let categories = [];
  try {
    categories = JSON.parse(raw).categories ?? [];
  } catch  {
    log("error", "bootstrap.parse_failed", {
      preview: raw.slice(0, 200)
    });
    return [];
  }
  log("info", "bootstrap.categories", {
    count: categories.length,
    titles: categories.map((c)=>c.title)
  });
  const created = [];
  for (const cat of categories){
    if (!cat.title || cat.title.trim().length < 8) continue;
    const { data, error } = await db.from("topics").insert({
      title: cat.title.trim(),
      tier: "global",
      tags: Array.isArray(cat.tags) ? cat.tags.slice(0, 6) : [],
      sources: [
        {
          type: "manual",
          label: "Auto-generated by classify-topic-drafts"
        }
      ],
      parent_topic_id: null
    }).select("id, title, tags, location_label, parent_topic_id").single();
    if (error) {
      log("warn", "bootstrap.insert_failed", {
        title: cat.title,
        error: error.message
      });
      continue;
    }
    created.push({
      ...data,
      child_count: 0
    });
    log("info", "bootstrap.created", {
      title: cat.title,
      id: data.id
    });
  }
  log("info", "bootstrap.done", {
    created: created.length
  });
  return created;
}
// ─── Phase 2: Classify orphan topics ─────────────────────────────────────────
const CLASSIFY_SYSTEM = `You are a news topic classifier.
Assign a micro-topic (a specific news story) to the most appropriate broad
parent category from the provided list.

Rules:
1. Only assign if confidence >= 0.75.
2. Return null if no parent fits well.
3. Never invent a parent not in the list.
4. Return ONLY valid JSON.

Format:
{
  "parent_topic_id": "<uuid or null>",
  "confidence": <0.0-1.0>,
  "reason": "<one sentence>"
}`;
const CONFIDENCE_THRESHOLD = 0.75;
const MIN_PARENTS = 3;
function buildPrompt(topic, parents) {
  const list = parents.map((p)=>{
    const tags = p.tags?.length ? p.tags.join(", ") : "no tags";
    return `  - id: "${p.id}" | "${p.title}" | tags: ${tags} | children: ${p.child_count}`;
  }).join("\n");
  const tags = topic.tags?.length ? topic.tags.join(", ") : "no tags";
  return `Parent categories:\n${list}\n\nClassify this topic:\n  Title: "${topic.title}"\n  Tags: ${tags}\n  Location: ${topic.location_label ?? "Global"}`;
}
// ─── Main handler ─────────────────────────────────────────────────────────────
Deno.serve(async (req)=>{
  if (req.method.toUpperCase() === "OPTIONS") return new Response(null, {
    status: 204,
    headers: CORS_HEADERS
  });
  if (req.method.toUpperCase() !== "POST") return json({
    ok: false,
    error: "Method Not Allowed"
  }, 405);
  const SUPABASE_URL = Deno.env.get("SUPABASE_URL") ?? Deno.env.get("PROJECT_URL") ?? "";
  const SERVICE_ROLE = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? Deno.env.get("SERVICE_ROLE_KEY") ?? "";
  const OPENAI_API_KEY = Deno.env.get("OPENAI_API_KEY") ?? "";
  if (!SUPABASE_URL || !SERVICE_ROLE) return json({
    ok: false,
    error: "Missing server env vars"
  }, 500);
  if (!OPENAI_API_KEY) return json({
    ok: false,
    error: "OPENAI_API_KEY not configured"
  }, 500);
  // ── Auth ──────────────────────────────────────────────────────────────────
  const authHeader = req.headers.get("Authorization") ?? "";
  const userJwt = authHeader.replace(/^Bearer\s+/i, "").trim();
  if (!userJwt) return json({
    ok: false,
    error: "Unauthorized"
  }, 401);
  let userId = null;
  try {
    const parts = userJwt.split(".");
    if (parts.length !== 3) throw new Error("Invalid JWT");
    const payload = parts[1].replace(/-/g, "+").replace(/_/g, "/");
    userId = JSON.parse(atob(payload + "=".repeat((4 - payload.length % 4) % 4))).sub ?? null;
  } catch  {
    return json({
      ok: false,
      error: "Invalid token"
    }, 401);
  }
  if (!userId) return json({
    ok: false,
    error: "No user ID in token"
  }, 401);
  const db = createClient(SUPABASE_URL, SERVICE_ROLE, {
    auth: {
      persistSession: false
    }
  });
  const { data: isAdmin, error: adminErr } = await db.rpc("is_admin", {
    uid: userId
  });
  if (adminErr || !isAdmin) {
    log("warn", "unauthorized", {
      user_id: userId,
      error: adminErr?.message
    });
    return json({
      ok: false,
      error: "Admin access required"
    }, 403);
  }
  log("info", "admin_verified", {
    user_id: userId
  });
  // ── Body params ───────────────────────────────────────────────────────────
  let batchLimit = 100;
  try {
    const body = await req.json();
    if (typeof body?.limit === "number") batchLimit = Math.min(500, Math.max(1, body.limit));
  } catch  {}
  const openai = new OpenAI({
    apiKey: OPENAI_API_KEY
  });
  // ── Fetch ALL orphan topics (parent_topic_id IS NULL, not itself a parent) ─
  // First get IDs of existing parent topics so we can exclude them
  const { data: existingParentsData } = await db.from("topics").select("id, title, tags, location_label, parent_topic_id").is("parent_topic_id", null);
  const allRootTopics = existingParentsData ?? [];
  // A root topic is a "parent" if at least one other topic points to it
  // We need to check this — fetch all topics with a parent_topic_id set
  const { data: assignedData } = await db.from("topics").select("parent_topic_id").not("parent_topic_id", "is", null);
  const parentIds = new Set((assignedData ?? []).map((r)=>r.parent_topic_id));
  // Split root topics into: existing parents vs true orphans
  let existingParents = allRootTopics.filter((t)=>parentIds.has(t.id)).map((t)=>({
      ...t,
      child_count: [
        ...assignedData ?? []
      ].filter((r)=>r.parent_topic_id === t.id).length
    }));
  // Also include manually-created parents (sources contains "manual") even with no children yet
  const { data: manualParentsData } = await db.from("topics").select("id, title, tags, location_label, parent_topic_id").is("parent_topic_id", null).contains("sources", [
    {
      type: "manual"
    }
  ]);
  const manualParentIds = new Set((manualParentsData ?? []).map((t)=>t.id));
  const manualOnlyParents = (manualParentsData ?? []).filter((t)=>!parentIds.has(t.id)).map((t)=>({
      ...t,
      child_count: 0
    }));
  let allParents = [
    ...existingParents,
    ...manualOnlyParents.filter((p)=>!existingParents.find((e)=>e.id === p.id))
  ];
  // Orphans = root topics that are NOT parents and NOT manually created parents
  const orphans = allRootTopics.filter((t)=>!parentIds.has(t.id) && !manualParentIds.has(t.id));
  log("info", "state", {
    orphans: orphans.length,
    existing_parents: allParents.length
  });
  if (orphans.length === 0) {
    return json({
      ok: true,
      phase1_created: 0,
      classified: 0,
      assigned: 0,
      skipped: 0,
      remaining: 0,
      message: "All topics are already assigned."
    });
  }
  // ── Phase 1: Bootstrap if too few parents ────────────────────────────────
  let phase1Created = 0;
  if (allParents.length < MIN_PARENTS) {
    log("info", "phase1.start", {
      existing: allParents.length
    });
    const newParents = await bootstrapParentTopics(orphans, db, openai);
    phase1Created = newParents.length;
    allParents = [
      ...allParents,
      ...newParents
    ];
    log("info", "phase1.done", {
      created: phase1Created,
      total: allParents.length
    });
  }
  if (allParents.length === 0) {
    return json({
      ok: false,
      error: "Failed to create parent topics. Check OPENAI_API_KEY and logs."
    }, 500);
  }
  // ── Phase 2: Classify orphans ─────────────────────────────────────────────
  const toClassify = orphans.slice(0, batchLimit);
  const remaining = orphans.length - toClassify.length;
  log("info", "phase2.start", {
    to_classify: toClassify.length,
    parents: allParents.length
  });
  let assigned = 0;
  let skipped = 0;
  const errors = [];
  const PARALLEL = 5;
  for(let i = 0; i < toClassify.length; i += PARALLEL){
    const batch = toClassify.slice(i, i + PARALLEL);
    await Promise.all(batch.map(async (topic)=>{
      try {
        const completion = await openai.chat.completions.create({
          model: "gpt-4o-mini",
          temperature: 0,
          max_tokens: 150,
          response_format: {
            type: "json_object"
          },
          messages: [
            {
              role: "system",
              content: CLASSIFY_SYSTEM
            },
            {
              role: "user",
              content: buildPrompt(topic, allParents)
            }
          ]
        });
        const raw = completion.choices[0]?.message?.content?.trim() ?? "{}";
        let parentId = null;
        let confidence = 0;
        try {
          const p = JSON.parse(raw);
          parentId = p.parent_topic_id ?? null;
          confidence = typeof p.confidence === "number" ? Math.max(0, Math.min(1, p.confidence)) : 0;
        } catch  {}
        const accepted = confidence >= CONFIDENCE_THRESHOLD && !!parentId;
        log("info", "classified", {
          title: topic.title,
          parentId,
          confidence,
          accepted
        });
        if (accepted) {
          const { error: updateErr } = await db.from("topics").update({
            parent_topic_id: parentId
          }).eq("id", topic.id);
          if (updateErr) {
            errors.push(`${topic.id}: ${updateErr.message}`);
            skipped++;
          } else {
            assigned++;
            // Update local parent child_count so later prompts reflect current state
            const p = allParents.find((p)=>p.id === parentId);
            if (p) p.child_count++;
          }
        } else {
          skipped++;
        }
      } catch (err) {
        errors.push(`${topic.id}: ${err?.message ?? String(err)}`);
        skipped++;
      }
    }));
  }
  const classified = assigned + skipped;
  const message = phase1Created > 0 ? `Created ${phase1Created} parent topics. Classified ${classified}: ${assigned} assigned, ${skipped} below threshold.${remaining > 0 ? ` ${remaining} remaining — run again.` : " All done!"}` : `Classified ${classified} topics: ${assigned} assigned, ${skipped} below threshold.${remaining > 0 ? ` ${remaining} remaining — run again.` : " All done!"}`;
  log("info", "done", {
    phase1_created: phase1Created,
    classified,
    assigned,
    skipped,
    remaining
  });
  return json({
    ok: true,
    phase1_created: phase1Created,
    classified,
    assigned,
    skipped,
    remaining,
    errors: errors.length > 0 ? errors.slice(0, 10) : undefined,
    message
  });
});
